/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, g++ 11.5.0 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:2.1-15.10" *)
module counter(clk, rst_n, count);
  (* src = "counter.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.12-4.17" *)
  input rst_n;
  wire rst_n;
  (* src = "counter.v:5.22-5.27" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:12.18-12.27|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:12.18-12.27|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _03_;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(count[0]),
    .Y(_02_[0])
  );
  sky130_fd_sc_hd__nand3_1 _05_ (
    .A(count[2]),
    .B(count[0]),
    .C(count[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _06_ (
    .A(count[3]),
    .B(_00_),
    .Y(_03_[3])
  );
  sky130_fd_sc_hd__a21oi_1 _07_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _08_ (
    .A(_00_),
    .SLEEP(_01_),
    .X(_03_[2])
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(count[0]),
    .B(count[1]),
    .X(_03_[1])
  );
  (* src = "counter.v:8.1-13.4" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:8.1-13.4" *)
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_03_[1]),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:8.1-13.4" *)
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(_03_[2]),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:8.1-13.4" *)
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(_03_[3]),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
  assign { _03_[31:5], _03_[0] } = { 27'h0000000, _02_[0] };
  assign _02_[31:1] = { 28'h0000000, count[3:1] };
endmodule
